### ISSUE TITLE
Stopped working in a recent Chrome update?

### ISSUE THREAD

**Issue by pbrown280** [jamesmortensen/random-gmail-quotes#8]
Hi

This extension seems to have stopped working in a recent Chrome update. I took a look at the dev tools but didn't see anything obvious, but then, I don't really know what I'm looking for.

Let me know what I can do to help investigate.

Thanks

**Comment by CrisVM** [comment]
Hi.

I'm also facing this issue. The extension stopped working.

Hey @jamesmortensen, is there anything we can do to help you troubleshoot?

Looking forward for an update on this.

Cheers.

**Comment by jamesmortensen** [comment]
Sorry to hear there's trouble, @CrisVM and @pbrown280 

I'm using macOS 13.6.6 and `Version 127.0.6533.100 (Official Build) (arm64)` of Google Chrome.  From what I can tell, everything is working just fine on my computer.  So I'm not able to replicate this.

What environments are you using?  What browser version?  OS?  Is it just initial composes, replies, or both that fail?  I've verified functionality works for initial composes and replies.

If you create a new browser profile and install the extension in the new profile, is the same problem there?  If it works, then try exporting the JSON quotes from the first profile and try importing into the second.  What I'm trying to rule out here is if anything corrupted the quotes data.  

Also, if you go to chrome://extensions/?id=kbjehpegjjfajhnommoeefdjhlhbgojh in the browser, do you see any errors reported?

Thank you and hope this helps!
James

**Comment by CrisVM** [comment]
I'm using Chrome version 127.0.6533.100 on both Windows 11 Pro, build 22631.3958 (23H2), and macOS 12.7.5 (installed via OpenCore Patcher, 'cause my Mac is really old).

Neither one works.

I have 2 profiles and I use the extension in the one with my personal e-mail only.

I've tried to install the extension in the other profile, but it didn't work either, even with the default quotes.

When I go to chrome://extensions/?id=kbjehpegjjfajhnommoeefdjhlhbgojh I can't see any errors or unusual UI.

![image](https://github.com/user-attachments/assets/636a8f16-dd08-46f7-960c-a12ba969a220)

Anything else I should try?

Thanks for your quick reply.

**Comment by pbrown280** [comment]
Hey James, thanks for your response.

I'm not near my computer right now so I can only give you anecdotal
evidence. I tried uninstalling and reinstalling the extension to no avail.
I do have multiple profiles but the extension is only installed in one of
them. I have it on two different computers- one is win 11 pro and the other
is win 10 pro. Chrome is syncing my profile on both.

I'm not sure of the exact chrome version but I generally keep it up to
date. I'll check this and the other things you mentioned when I get home
tonight.

Thanks,

Paul


Paul T Brown | ***@***.***

Stark raving sane

**Comment by pbrown280** [comment]
Hi again,

I've just set up my same Google account on my work MacBook Pro.

Chrome version: Version 127.0.6533.100 (Official Build) (arm64)
Mac details: M3 silicon chip, Mac OS Sonoma 14.6.1

On this machine I just have the default set of quotes; I haven't made any
changes at all. Still no joy; simply nothing when I compose a new message
or a reply.

No errors when I go to the chrome://extensions page you mentioned, and I
still don't see anything interesting in dev tools.

Thanks,


Paul T Brown | ***@***.***

A man who has never gone to school may steal from a freight car; but if he has a university education, he may steal the whole railroad.  - Theodore Roosevelt

**Comment by pbrown280** [comment]
Hi,

Here's the Chrome version on both my Win 10 Pro and Win 11 Pro
machines: Version 127.0.6533.100 (Official Build) (64-bit)

I also tried installing the extension into a new profile. Same thing -
nothing happens at all when I compose a new message or a reply/forward.

Let me know if there's anything else I can do to help.

Thanks,


Paul T Brown | ***@***.***

Should it not be considered odd that the poor in America today are more likely to be obese than emaciated?

**Comment by rkampen** [comment]
I am having the same issue. I am on a Mac OS 14.5, Chrome Version 127.0.6533.100 (Official Build) (arm64).

I wonder if this screenshot that reveals the error helps.

![CleanShot 2024-08-13 at 14 17 24](https://github.com/user-attachments/assets/41b12fec-0ecb-4dfc-ac1d-1a84de011be4)

**Comment by pbrown280** [comment]
Hey, that's a great find! I can't tell what tool that screenshot is from -
can you share how you got that? It doesn't seem to be from any of the tabs
in the standard Chrome dev tools.

Really hope this helps James to find a way to resolve the problem  :)

Paul T Brown | ***@***.***

There are no atheists in foxholes

**Comment by rkampen** [comment]
If you go to chrome://extensions/, look at the relevant extension, and if there is an "Errors" button, click on it, and you'll get to the page I did. 

That help?

**Comment by pbrown280** [comment]
Ah, yes, James mentioned looking for errors on that page. I don't see
anything there. Do you have to do anything specific to get it to show up or
am I just an enemy of the universe? haha

Paul T Brown | ***@***.***

A tendency to melancholy, let it be observed, is a misfortune, not a fault.
- Abraham Lincoln

**Comment by CrisVM** [comment]
Hey guys,

After your first post @rkampen, I've made a little research and found this: https://developer.chrome.com/blog/mutation-events-deprecation

In short, this confirms the event "DOMNodeInserted" (highlighted in your screenshot) is no longer supported in Chrome, among other "mutation events".

The page has some examples of how to replace the unsupported calls with new supported ones and a link to the official docs in the section "How to migrate".

Please, have a look at this when you can @jamesmortensen.

Thanks for your time and effort to put this amazing extension together and shared it with the world.

Cheers.
Cris.

**Comment by CrisVM** [comment]
@pbrown280 and @rkampen

Just for curiosity's sake, I've found another way to see the error: just use the dev tools' console:

![image](https://github.com/user-attachments/assets/4aa42d1d-6311-40a1-9d33-fcdab40c9fc3)

But I still can't see any errors in the extension details page:

![image](https://github.com/user-attachments/assets/7bbdce76-c942-47d4-84be-338a4e7880c6)

**Comment by pbrown280** [comment]
That's a good catch @CrisVM but I'm not seeing this even on the Console tab
in Dev Tools either. I wonder if the extension itself is being blocked or
something? Anyone know how I can check that? I have already removed and
reinstaled it (a few times) so if there is something like that going on, it
must be a persistent thing - and applying across devices, too.

Thanks!

Paul T Brown | ***@***.***

The quickest way of ending a war is to lose it. - George Orwell

**Comment by pbrown280** [comment]
ok, just to update, I do indeed see the error after all (in Dev Tools, but
still not on the Manage Extension page). It was just a bit of a needle in a
haystack because there's loads and loads of errors occurring, probably
because I have too many extensions.

Apologies for the red herring, especially if anyone went down the rabbit
hole because of it!

Paul T Brown | ***@***.***

For this you threw off a king? - Mark Steyn

**Comment by jamesmortensen** [comment]
Thanks for the efforts in the research, @CrisVM and @pbrown280 -- I believe you're not seeing the error in the "Errors" section of the Extensions page because it's just not firing anything.  It's just triggering a deprecation notice in the developer console, but that isn't in itself causing a problem.  

I don't yet see these errors in my copy of Google Chrome (not sure why) but the deprecation notice and work you did is enough to help me understand the problem.  

My plan is to use this polyfill, which allows the existing code to work by essentially re-implementing the missing functionality using MutationObservers (which are the replacement for mutation events).  https://github.com/mfreed7/mutation-events-polyfill#readme

I will get to this when I can.  I'll document the plan below, if someone wanted to take a stab at trying to fix it before I'm able to get to it.

 ## The plan I have is this:

### Option 1 - Use a polyfill to monkey patch the deprecated functionality

- Install the mutation observer polyfill `npm i mutation-events` (See https://www.npmjs.com/package/mutation-events)
- Add it to the extension package.
- Clone the random-gmail-quotes repo and load in Chrome as an unpacked extension ("Developer Mode" must be enabled in chrome://extensions)
- Inject the mutation-events.min.js script as a content script into pages with the domain mail.google.com.

```
<script src="mutation_events.min.js"></script>
<div id=target></div>
<script>
target.addEventListener('DOMNodeInserted',() => {});
</script>
```

- Attempt to see if the quote inject functionality returns.

### Alternative Option 2 - Replace the deprecated/removed functionality with MutationObservers

Alternatively, instead of using the polyfill, we might try replacing the DOMNodeInserted event listener with the MutationObserver codebase.  In `js/randomQuoteContentScript.js` that would be this block of code on line 156:

```
    /**
     * When DOM nodes are inserted in the page, look for a compose window and inject.
     */
    window.addEventListener("DOMNodeInserted", function () {
        injectQuoteInTextarea();
    }, false);
```

and replacing those lines with:

```
    /**
     * When DOM nodes are inserted in the page, look for a compose window and inject.
     */
const observer = new MutationObserver(mutationList =>  
  mutationList.filter(m => m.type === 'childList').forEach(m => {  
      injectQuoteInTextarea();
  }));  
observer.observe(target,{childList: true, subtree: true});  
```

The changes sound simple, but from past experiences with browser extension development, I know that this would probably take a few hours, maybe more, for me to tweak in order to get it to function properly, and it may take someone else more time in order to understand the code.

**Comment by jamesmortensen** [comment]
@CrisVM and @pbrown280 -- Good news. I believe the issue should now be resolved in v2.0.3.  The extension has to go through Google's extension review process and once completed, should auto-update in your browser.  Please look for it to start working again shortly.

Thanks again for the debugging help!

**Comment by pbrown280** [comment]
Hi James, Thank you so much for the quick fix! I got 2.0.3 this morning and
can confirm that it's working as expected.

If you have a tip jar, I'm happy to send you a little something for a
coffee or a beer. :)

Cheers!

Paul


Paul T Brown | ***@***.***

Honk if you like being told what to do

**Comment by jamesmortensen** [comment]
Happy to hear Google reviewed, and released, the update so quickly and that it works again for you!  It's also great to hear that something I built to solve a problem for myself is so useful for others as well.  

There's a couple ways you could send me money. I'm not sure where you're located and if these options work outside the U.S. though:

- Paypal:  https://paypal.me/jmort253
- Venmo:  @jmort253
- Cash App:  $jmort253

Thanks for confirming it is working,
James

**Comment by jamesmortensen** [comment]
@rkampen Sorry, I didn't mean to fail to acknowledge you. Thank you for the screenshot.  Hope the extension is working for you as well.  Cheers!

**Comment by CrisVM** [comment]
Hey guys.

I can also confirm the extension works for me again.

Thank you so much, @jamesmortensen.

Cheers.
Cris

**Comment by rkampen** [comment]
Thanks, @jamesmortensen, for your labours! It all works fine now on my side too.

Ryan
